import SwiftUI

// Page views for the exported Spending & Waste PDF. Each is pinned to US-Letter (612 × 792 pt),
// uses only static `Sourdough.Ramp.*` colours (deterministic under `ImageRenderer`), and is
// rendered with `.environment(\.colorScheme, .light)` by `StatsPDFReport`.

enum ReportLayout {
    static let pageWidth: CGFloat = 612
    static let margin: CGFloat = 40
    static let blockGap: CGFloat = 18
}

private let reportDateFormatter: DateFormatter = {
    let f = DateFormatter()
    f.dateStyle = .long
    f.timeStyle = .none
    return f
}()

// MARK: - Shared chrome

/// Content-height page — the PDF media box is set per page, so it just needs a fixed width.
private struct ReportPage<Content: View>: View {
    @ViewBuilder let content: () -> Content

    var body: some View {
        VStack(alignment: .leading, spacing: ReportLayout.blockGap) {
            content()
        }
        .padding(ReportLayout.margin)
        .frame(width: ReportLayout.pageWidth, alignment: .topLeading)
        .background(Sourdough.Ramp.linen50)
    }
}

private struct ReportCard<Content: View>: View {
    var spacing: CGFloat = Sourdough.Spacing.rowInternals
    var ground: Color = Sourdough.Ramp.linen100
    @ViewBuilder let content: () -> Content

    var body: some View {
        VStack(alignment: .leading, spacing: spacing) {
            content()
        }
        .padding(Sourdough.Spacing.screenMargin)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(ground)
        .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.hero, style: .continuous))
    }
}

private func reportHeader(_ kicker: String, _ title: String) -> some View {
    VStack(alignment: .leading, spacing: 4) {
        Text(kicker.uppercased())
            .sourdoughTextStyle(.sectionHead, color: Sourdough.Ramp.linen500)
        Text(title)
            .sourdoughTextStyle(.title1, color: Sourdough.Ramp.linen900)
    }
}

private func reportFooter(_ now: Date) -> some View {
    Text("Generated by Use Up · \(reportDateFormatter.string(from: now))")
        .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen400)
        .frame(maxWidth: .infinity, alignment: .center)
}

private func legendSwatch(_ color: Color, _ label: String) -> some View {
    HStack(spacing: Sourdough.Spacing.iconToLabel) {
        RoundedRectangle(cornerRadius: 2, style: .continuous).fill(color).frame(width: 8, height: 8)
        Text(label).sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen500)
    }
}

private func reportStatCard<Trailing: View>(
    label: String,
    value: String,
    valueColor: Color,
    ground: Color,
    @ViewBuilder trailing: @escaping () -> Trailing
) -> some View {
    ReportCard(spacing: Sourdough.Spacing.insideChip, ground: ground) {
        Text(label.uppercased())
            .sourdoughTextStyle(.sectionHead, color: Sourdough.Ramp.linen500)
        Text(value)
            .sourdoughTextStyle(.title1, color: valueColor)
            .monospacedDigit()
            .lineLimit(1)
            .minimumScaleFactor(0.6)
        trailing()
    }
}

// MARK: - Cover

struct StatsReportCoverPage: View {
    let events: [PantryEvent]
    let now: Date

    private var totals: StatsTotals { StatsTotals.allTime(events) }

    private var rangeText: String {
        guard let earliest = events.map(\.occurredAt).min() else { return "" }
        return "\(reportDateFormatter.string(from: earliest)) – \(reportDateFormatter.string(from: now))"
    }

    var body: some View {
        ReportPage {
            Spacer().frame(height: 48)

            VStack(alignment: .leading, spacing: Sourdough.Spacing.insideChip) {
                Text("Use Up")
                    .sourdoughTextStyle(.display, color: Sourdough.Ramp.linen900)
                Text("Spending & Waste Report")
                    .sourdoughTextStyle(.title2, color: Sourdough.Ramp.terracotta600)
                Text(rangeText)
                    .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen500)
            }

            Spacer().frame(height: 40)

            HStack(alignment: .top, spacing: Sourdough.Spacing.rowInternals) {
                summaryTile("Total spent", totals.spent.asHedgedDollar, Sourdough.Ramp.linen900)
                summaryTile("Total binned", totals.wasted.asHedgedDollar, Sourdough.Ramp.terracotta600)
                summaryTile("Waste rate", totals.wasteRate.map { "\($0)%" } ?? "—", Sourdough.Ramp.terracotta600)
            }

            Spacer().frame(height: 120)

            Text("Costs are estimated from typical grocery prices, not receipts.")
                .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen400)

            reportFooter(now)
        }
    }

    private func summaryTile(_ label: String, _ value: String, _ color: Color) -> some View {
        ReportCard(spacing: Sourdough.Spacing.insideChip) {
            Text(label.uppercased())
                .sourdoughTextStyle(.sectionHead, color: Sourdough.Ramp.linen500)
            Text(value)
                .sourdoughTextStyle(.title1, color: color)
                .monospacedDigit()
                .lineLimit(1)
                .minimumScaleFactor(0.5)
        }
    }
}

// MARK: - Period

struct StatsReportPeriodPage: View {
    let period: StatsPeriod
    let events: [PantryEvent]
    let now: Date

    private var stats: PeriodStats {
        PeriodStats.make(events: events, period: period, selectedIndex: nil, now: now)
    }

    private var totalSpend: Double { stats.bars.reduce(0) { $0 + $1.spend } }
    private var totalWaste: Double { stats.bars.reduce(0) { $0 + $1.waste } }

    var body: some View {
        ReportPage {
            reportHeader(period.title, stats.chartTitle)

            Text("\(stats.chartTitle) total: \(totalSpend.asHedgedDollar) spent · \(totalWaste.asHedgedDollar) binned")
                .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen500)

            HStack(alignment: .top, spacing: Sourdough.Spacing.rowInternals) {
                reportStatCard(
                    label: "Spent \(period.perLabel)",
                    value: stats.headlineSpend.asHedgedDollar,
                    valueColor: Sourdough.Ramp.linen900,
                    ground: Sourdough.Ramp.linen100
                ) {
                    if let pct = stats.spendTrendPct {
                        Text("\(pct >= 0 ? "▲" : "▼") \(abs(pct))% vs last \(period.perWord)")
                            .sourdoughTextStyle(.caption, color: pct >= 0 ? Sourdough.Ramp.terracotta600 : Sourdough.Ramp.sage600)
                    } else {
                        Text("no prior \(period.perWord)")
                            .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen400)
                    }
                }
                reportStatCard(
                    label: "Binned \(period.perLabel)",
                    value: stats.headlineWaste.asHedgedDollar,
                    valueColor: Sourdough.Ramp.terracotta600,
                    ground: Sourdough.Ramp.terracotta50
                ) {
                    if let pct = stats.wastePctOfSpend {
                        Text("\(pct)% of what you spent")
                            .sourdoughTextStyle(.caption, color: Sourdough.Ramp.terracotta600)
                    } else {
                        Text("nothing binned")
                            .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen400)
                    }
                }
            }

            ReportCard {
                HStack(alignment: .top) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Each bar is one \(period.perWord)")
                            .sourdoughTextStyle(.rowTitle, color: Sourdough.Ramp.linen900)
                        Text("Split into what you ate and what you binned")
                            .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen500)
                    }
                    Spacer(minLength: 0)
                    VStack(alignment: .leading, spacing: 3) {
                        legendSwatch(Sourdough.Ramp.sage200, "Eaten")
                        legendSwatch(Sourdough.Ramp.terracotta500, "Binned")
                    }
                }
                StatsBarChart(stats: stats, animated: false, onSelectBar: { _ in })
            }

            ReportCard {
                Text("Where the waste goes")
                    .sourdoughTextStyle(.rowTitle, color: Sourdough.Ramp.linen900)
                Text(stats.donutCaption(isolated: nil))
                    .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen500)

                if stats.slices.isEmpty {
                    Text("Nothing binned in this period.")
                        .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen400)
                } else {
                    HStack(alignment: .center, spacing: Sourdough.Spacing.betweenBlocks) {
                        StatsDonut(
                            slices: stats.slices,
                            isolatedIndex: nil,
                            centre: stats.donutCentre(isolated: nil)
                        )
                        VStack(spacing: Sourdough.Spacing.insideChip) {
                            ForEach(stats.slices) { slice in
                                HStack(spacing: 7) {
                                    RoundedRectangle(cornerRadius: 3, style: .continuous)
                                        .fill(slice.color).frame(width: 9, height: 9)
                                    Text(slice.name)
                                        .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen900)
                                    Spacer(minLength: 4)
                                    Text(slice.amount.asHedgedDollar)
                                        .sourdoughTextStyle(.numeric, color: Sourdough.Ramp.linen900)
                                    Text("\(Int((slice.amount / max(stats.binnedTotal, 0.01) * 100).rounded()))%")
                                        .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen500)
                                        .frame(width: 34, alignment: .trailing)
                                }
                            }
                        }
                    }
                }
            }

            if period == .yearly && !StatsReadiness.yearlyAvailable(events, now: now) {
                Text("Less than a full year of history — these bars are partial.")
                    .sourdoughTextStyle(.caption, color: Sourdough.Ramp.honey700)
            }

            reportFooter(now)
        }
    }
}

// MARK: - Most thrown-away

struct StatsReportOffendersPage: View {
    let events: [PantryEvent]
    let now: Date

    private var rows: [StatsOffender] {
        PeriodStats.mostWasted(events: events, limit: 12, now: now)
    }

    var body: some View {
        ReportPage {
            reportHeader("Most thrown-away", "Last 6 months")

            if rows.isEmpty {
                ReportCard {
                    Text("No repeat waste in the last 6 months — nice work.")
                        .sourdoughTextStyle(.subhead, color: Sourdough.Ramp.linen500)
                }
            } else {
                ReportCard(spacing: 0) {
                    ForEach(Array(rows.enumerated()), id: \.element.id) { index, offender in
                        if index > 0 {
                            Divider().overlay(Sourdough.Ramp.linen200)
                        }
                        offenderRow(rank: index + 1, offender)
                    }
                }
            }

            Text("Counts every time an ingredient was logged as binned; rate is binned ÷ bought.")
                .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen400)
                .padding(.top, Sourdough.Spacing.insideChip)
            reportFooter(now)
        }
    }

    private func offenderRow(rank: Int, _ o: StatsOffender) -> some View {
        HStack(spacing: Sourdough.Spacing.rowInternals) {
            Text("\(rank)")
                .sourdoughTextStyle(.numeric, color: Sourdough.Ramp.linen500)
                .frame(width: 22, alignment: .leading)

            VStack(alignment: .leading, spacing: 4) {
                Text(o.name.capitalized)
                    .sourdoughTextStyle(.rowTitle, color: Sourdough.Ramp.linen900)
                    .lineLimit(1)
                HStack(spacing: 6) {
                    GeometryReader { proxy in
                        ZStack(alignment: .leading) {
                            Capsule().fill(Sourdough.Ramp.linen200)
                            Capsule().fill(o.barColor)
                                .frame(width: proxy.size.width * CGFloat(min(max(o.rate, 0), 1)))
                        }
                    }
                    .frame(height: 4)
                    Text("binned \(o.wastedCount) of \(o.boughtCount) bought")
                        .sourdoughTextStyle(.caption, color: Sourdough.Ramp.linen500)
                        .fixedSize()
                }
            }

            Text(o.wastedCost.asHedgedDollar)
                .sourdoughTextStyle(.numeric, color: Sourdough.Ramp.terracotta600)
        }
        .padding(.vertical, Sourdough.Spacing.insideChip)
    }
}
