import SwiftUI
import PhosphorSwift

#Preview("Recipe Detail") {
    PreviewContainer {
        NavigationStack {
            RecipeDetailView(recipe: DummyData.sampleSavedRecipes[0])
        }
    }
}

struct RecipeDetailView: View {
    @EnvironmentObject private var savedRecipesStore: SavedRecipesStore
    @EnvironmentObject private var pantryStore: PantryStore
    @EnvironmentObject private var activityStore: UserActivityStore
    @EnvironmentObject private var session: AppSession
    @Environment(\.dismiss) private var dismiss
    let recipe: Recipe
    @State private var showRatingSheet = false
    @State private var showRatings = false
    @State private var showGroceryList = false
    @State private var showSaveChoiceSheet = false
    @State private var showCollectionPicker = false
    @State private var pendingSaveSheetWork: DispatchWorkItem? = nil
    @State private var showPDFShare = false
    @State private var pdfURL: URL?
    @State private var showPaywall = false
    @State private var isCooking = false
    @State private var checkedIngredients: Set<UUID> = []
    @State private var selectedTab: RecipeTab = .ingredients
    @State private var showReportSheet = false
    @State private var reportError: String?
    @State private var showDeleteAlert = false
    @State private var showBlockAlert = false
    @State private var blockError: String?

    private enum RecipeTab: CaseIterable {
        case ingredients, instructions
        var label: String {
            switch self {
            case .ingredients: return "Ingredients"
            case .instructions: return "Instructions"
            }
        }
    }

    private var topSafeInset: CGFloat {
        UIApplication.shared.connectedScenes
            .compactMap { $0 as? UIWindowScene }
            .first(where: { $0.activationState == .foregroundActive })?
            .keyWindow?
            .safeAreaInsets.top ?? 59
    }

    private var currentRecipe: Recipe {
        savedRecipesStore.sharedRecipes.first(where: { $0.id == recipe.id })
            ?? savedRecipesStore.savedRecipes.first(where: { $0.id == recipe.id })
            ?? savedRecipesStore.communityRecipes.first(where: { $0.id == recipe.id })
            ?? recipe
    }

    var body: some View {
        ZStack(alignment: .bottom) {
            ScrollView(.vertical, showsIndicators: false) {
                VStack(spacing: 0) {
                    heroSection
                    statsBar
                    if recipe.isAIGenerated {
                        HStack(spacing: Sourdough.Spacing.insideChip) {
                            Ph.sparkle.regular
                                .frame(width: 12, height: 12)
                                .foregroundStyle(Sourdough.Colors.mutedInk)
                            Text("This recipe was generated by AI and may contain inaccuracies. Use your best judgment.")
                                .foregroundStyle(Sourdough.Colors.mutedInk)
                                .sourdoughTextStyle(.caption)
                        }
                        .padding(.horizontal, Sourdough.Spacing.screenMargin)
                        .padding(.vertical, Sourdough.Spacing.rowInternals)
                    }
                    Divider()
                    if !recipe.isAIGenerated && recipe.isUserShared {
                        ratingRow
                    }
                    tabBar
                    Group {
                        switch selectedTab {
                        case .ingredients:
                            ingredientsSection
                            if recipe.isAIGenerated && !recipe.substitutions.isEmpty {
                                Divider()
                                substitutionsSection
                            }
                        case .instructions:
                            VStack(spacing: 0) {
                                stepsSection
                                if !recipe.sources.isEmpty {
                                    sourcesSection
                                }
                            }
                        }
                    }
                    .simultaneousGesture(
                        DragGesture(minimumDistance: 24)
                            .onEnded { value in
                                let horizontal = value.translation.width
                                let vertical = value.translation.height
                                guard abs(horizontal) > abs(vertical) * 2, abs(horizontal) > 50 else { return }
                                if horizontal < 0, selectedTab == .ingredients {
                                    withAnimation(.easeInOut(duration: 0.2)) { selectedTab = .instructions }
                                } else if horizontal > 0, selectedTab == .instructions {
                                    withAnimation(.easeInOut(duration: 0.2)) { selectedTab = .ingredients }
                                }
                            }
                    )
                }
                .padding(.bottom, 100)
            }
            cookingButton
        }
        .ignoresSafeArea(edges: [.top, .bottom])
        .background(Sourdough.Colors.canvas)
        .toolbar(.hidden, for: .navigationBar)
        .preference(key: HideTabBarKey.self, value: true)
        .background(SwipeBackEnabler())
        .navigationDestination(isPresented: $showRatings) {
            RecipeRatingsView(recipe: currentRecipe)
        }
        .navigationDestination(isPresented: $showGroceryList) {
            GroceryListView(recipe: currentRecipe)
        }
        .task {
            await savedRecipesStore.fetchCommunityReviews(for: recipe.id)
        }
        .sheet(isPresented: $showRatingSheet) {
            RateRecipeSheet(
                recipe: recipe,
                currentRating: Int(currentRecipe.userRating ?? 0),
                currentReview: currentRecipe.review ?? ""
            ) { rating, review in
                savedRecipesStore.rateRecipe(recipe, rating: rating, review: review)
            }
            .presentationDetents([.medium])
        }
        .sheet(isPresented: $showSaveChoiceSheet) {
            SaveChoiceSheet(
                onSaveToCollection: {
                    showSaveChoiceSheet = false
                    pendingSaveSheetWork?.cancel()
                    let work = DispatchWorkItem { showCollectionPicker = true }
                    pendingSaveSheetWork = work
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.45, execute: work)
                },
                onJustSave: {
                    recipe.isAIGenerated ? savedRecipesStore.saveGeneratedRecipe(recipe) : savedRecipesStore.saveRecipe(recipe)
                    showSaveChoiceSheet = false
                }
            )
            .presentationDetents([.height(220)])
        }
        .sheet(isPresented: $showCollectionPicker) {
            CollectionPickerSheet(recipe: recipe) {
                showCollectionPicker = false
            }
            .presentationDetents([.medium, .large])
        }
        .sheet(isPresented: $showPDFShare) {
            if let pdfURL {
                ShareSheet(items: [pdfURL])
            }
        }
        .sheet(isPresented: $showPaywall) {
            UseUpPaywallView(onDismiss: { showPaywall = false })
        }
        .sheet(isPresented: $showReportSheet) {
            ReportContentSheet(subject: .recipe(name: recipe.title)) { category, description in
                Task {
                    do {
                        try await savedRecipesStore.reportRecipe(recipe, category: category, description: description)
                    } catch {
                        reportError = error.localizedDescription.contains("duplicate") || error.localizedDescription.contains("unique")
                            ? "You've already reported this recipe."
                            : "Failed to submit report. Please try again."
                    }
                }
            }
            .presentationDetents([.medium])
            .presentationDragIndicator(.visible)
        }
        .alert("Delete Recipe?", isPresented: $showDeleteAlert) {
            Button("Delete", role: .destructive) {
                savedRecipesStore.deleteRecipe(recipe)
                dismiss()
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("\"\(recipe.title)\" will be permanently deleted and cannot be recovered.")
        }
        .reportErrorAlert($reportError)
        .alert("Block \(recipe.createdByName ?? "this user")?", isPresented: $showBlockAlert) {
            Button("Block", role: .destructive) {
                guard let creatorIdString = recipe.createdBy, let creatorId = UUID(uuidString: creatorIdString) else { return }
                Task {
                    do {
                        try await savedRecipesStore.blockUser(creatorId)
                        dismiss()
                    } catch {
                        blockError = "Failed to block user. Please try again."
                    }
                }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("You won't see recipes or reviews from this user anymore. You can unblock them anytime in Settings.")
        }
        .alert("Block Error", isPresented: Binding(
            get: { blockError != nil },
            set: { if !$0 { blockError = nil } }
        )) {
            Button("OK") { blockError = nil }
        } message: {
            if let err = blockError { Text(err) }
        }
    }

    // MARK: - Hero Section

    private var heroSection: some View {
        GeometryReader { proxy in
            ZStack(alignment: .bottom) {
                // Full-bleed image
                Group {
                    if recipe.isAIGenerated && recipe.imageData == nil && recipe.imagePath == nil {
                        RecipeImagePlaceholder()
                    } else {
                        CachedRecipeImage(
                            recipeID: recipe.id,
                            imageData: recipe.imageData,
                            imagePath: recipe.imagePath
                        )
                    }
                }
                .frame(width: proxy.size.width, height: 320 + topSafeInset)
                .clipped()

                // Dark gradient overlay
                LinearGradient(
                    stops: [
                        .init(color: .clear, location: 0.3),
                        .init(color: .black.opacity(0.85), location: 1)
                    ],
                    startPoint: .top,
                    endPoint: .bottom
                )
                .frame(width: proxy.size.width, height: 320 + topSafeInset)
                .allowsHitTesting(false)

                // Title / labels block
                VStack(alignment: .leading, spacing: Sourdough.Spacing.insideChip) {
                    let allLabels: [String] = {
                        var labels: [String] = []
                        if recipe.dietType != "any" { labels.append(recipe.dietType.uppercased()) }
                        labels += recipe.dietaryRestrictions.map { $0.uppercased() }
                        return labels
                    }()
                    if !allLabels.isEmpty {
                        ScrollView(.horizontal, showsIndicators: false) {
                            HStack(spacing: 4) {
                                ForEach(allLabels.indices, id: \.self) { i in
                                    OnDarkBadge(text: allLabels[i])
                                }
                            }
                        }
                    }

                    Text(recipe.title)
                        .foregroundStyle(Sourdough.Colors.heroTitleOnDark)
                        .sourdoughTextStyle(.title1)

                    Text(recipe.summary)
                        .foregroundStyle(Sourdough.Colors.heroMetaOnDark)
                        .sourdoughTextStyle(.body)
                        .lineLimit(2)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.horizontal, Sourdough.Spacing.screenMargin)
                .padding(.bottom, Sourdough.Spacing.screenMargin)

            }
            .frame(height: 320, alignment: .bottom)
            .overlay(alignment: .top) {
                HStack(spacing: Sourdough.Spacing.insideChip) {
                    Button { dismiss() } label: {
                        Ph.caretLeft.regular
                            .frame(width: 16, height: 16)
                            .foregroundStyle(Sourdough.Ramp.linen900)
                            .frame(width: 40, height: 40)
                            .background(Sourdough.Ramp.linen0)
                            .clipShape(Circle())
                    }
                    .buttonStyle(.plain)

                    Spacer()

                    Button {
                        if session.isPremium {
                            pdfURL = generatePDF()
                            if pdfURL != nil { showPDFShare = true }
                        } else {
                            showPaywall = true
                        }
                    } label: {
                        Ph.export.regular
                            .frame(width: 16, height: 16)
                            .foregroundStyle(Sourdough.Ramp.linen900)
                            .frame(width: 40, height: 40)
                            .background(Sourdough.Ramp.linen0)
                            .clipShape(Circle())
                    }
                    .buttonStyle(.plain)

                    let isSaved = savedRecipesStore.isSaved(recipe)
                    Button {
                        if isSaved {
                            savedRecipesStore.unsaveRecipe(recipe)
                        } else {
                            showSaveChoiceSheet = true
                        }
                    } label: {
                        (isSaved ? Ph.bookmark.fill : Ph.bookmark.regular)
                            .frame(width: 16, height: 16)
                            .foregroundStyle(isSaved ? Sourdough.Ramp.sage600 : Sourdough.Ramp.linen900)
                            .frame(width: 40, height: 40)
                            .background(Sourdough.Ramp.linen0)
                            .clipShape(Circle())
                    }
                    .buttonStyle(.plain)

                    Button {
                        showGroceryList = true
                    } label: {
                        Ph.shoppingCart.regular
                            .frame(width: 16, height: 16)
                            .foregroundStyle(Sourdough.Ramp.linen900)
                            .frame(width: 40, height: 40)
                            .background(Sourdough.Ramp.linen0)
                            .clipShape(Circle())
                    }
                    .buttonStyle(.plain)

                    let isOwner = recipe.createdBy == savedRecipesStore.userId?.uuidString
                    if isOwner {
                        Button { showDeleteAlert = true } label: {
                            Ph.trash.regular
                                .frame(width: 16, height: 16)
                                .foregroundStyle(Sourdough.Ramp.linen900)
                                .frame(width: 40, height: 40)
                                .background(Sourdough.Ramp.linen0)
                                .clipShape(Circle())
                        }
                        .buttonStyle(.plain)
                    }

                    if recipe.isUserShared && !isOwner {
                        Menu {
                            Button {
                                showReportSheet = true
                            } label: {
                                Label {
                                    Text("Report")
                                } icon: {
                                    Ph.flag.regular
                                        .frame(width: 16, height: 16)
                                }
                            }

                            Button(role: .destructive) {
                                showBlockAlert = true
                            } label: {
                                Label {
                                    Text("Block")
                                } icon: {
                                    Ph.prohibit.regular
                                        .frame(width: 16, height: 16)
                                }
                            }
                        } label: {
                            Ph.dotsThree.regular
                                .rotationEffect(.degrees(90))
                                .frame(width: 16, height: 16)
                                .foregroundStyle(Sourdough.Ramp.linen900)
                                .frame(width: 40, height: 40)
                                .background(Sourdough.Ramp.linen0)
                                .clipShape(Circle())
                        }
                    }
                }
                .padding(.horizontal, Sourdough.Spacing.rowInternals)
                .padding(.top, topSafeInset + Sourdough.Spacing.rowInternals)
            }
        }
        .frame(height: 320)
    }

    // MARK: - Stats Bar

    private var statsBar: some View {
        HStack(spacing: 0) {
            statCol(icon: .clock, value: "\(recipe.timeMinutes) min", label: "TOTAL")
            statDivider
            statCol(icon: .users, value: "\(recipe.servings)", label: "SERVINGS")
            statDivider
            statCol(icon: .flame, value: "\(recipe.macros.calories)", label: "CALORIES")
            statDivider
            statCol(icon: .forkKnife, value: "\(recipe.macros.proteinG)g", label: "PROTEIN")
        }
        .padding(.vertical, Sourdough.Spacing.rowInternals)
    }

    private func statCol(icon: Ph, value: String, label: String) -> some View {
        VStack(spacing: 4) {
            icon.regular
                .frame(width: 14, height: 14)
                .foregroundStyle(Sourdough.Colors.mutedInk)
            Text(value)
                .foregroundStyle(Sourdough.Colors.ink)
                .sourdoughTextStyle(.rowTitle)
            Text(label)
                .foregroundStyle(Sourdough.Colors.faintInk)
                .sourdoughTextStyle(.caption)
        }
        .frame(maxWidth: .infinity)
    }

    private var statDivider: some View {
        Rectangle()
            .fill(Sourdough.Colors.hairline)
            .frame(width: 1, height: 32)
    }

    // MARK: - Rating Row

    private var ratingRow: some View {
        HStack(spacing: Sourdough.Spacing.insideChip) {
            Button {
                showRatings = true
            } label: {
                let reviewCount = savedRecipesStore.communityReviews[currentRecipe.id]?.count ?? 0
                HStack(spacing: Sourdough.Spacing.iconToLabel) {
                    StarRatingView(rating: currentRecipe.rating, size: 18)
                    if currentRecipe.rating > 0 {
                        Text(currentRecipe.rating.truncatingRemainder(dividingBy: 1) == 0
                             ? String(format: "%.0f", currentRecipe.rating)
                             : String(format: "%.1f", currentRecipe.rating))
                            .foregroundStyle(Sourdough.Colors.ink)
                            .sourdoughTextStyle(.numeric)
                    }
                    Text("·")
                        .foregroundStyle(Sourdough.Colors.faintInk)
                    Text("\(reviewCount) \(reviewCount == 1 ? "review" : "reviews")")
                        .foregroundStyle(Sourdough.Colors.mutedInk)
                        .sourdoughTextStyle(.caption)
                }
            }
            .buttonStyle(.plain)

            Spacer()

            let creatorName = recipe.createdByName ?? recipe.createdBy ?? "UseUp"
            HStack(spacing: 3) {
                Text("by")
                    .foregroundStyle(Sourdough.Colors.mutedInk)
                    .sourdoughTextStyle(.caption)
                Text(creatorName)
                    .foregroundStyle(Sourdough.Colors.ink)
                    .sourdoughTextStyle(.numeric)
            }

            if currentRecipe.userRating == nil {
                Button {
                    showRatingSheet = true
                } label: {
                    Text("Rate It")
                        .foregroundStyle(Sourdough.Colors.actionInk)
                        .sourdoughTextStyle(.caption)
                }
                .buttonStyle(.plain)
            }
        }
        .padding(.horizontal, Sourdough.Spacing.screenMargin)
        .padding(.vertical, Sourdough.Spacing.rowInternals)
    }

    // MARK: - Tab Bar

    private var tabBar: some View {
        HStack(spacing: Sourdough.Spacing.iconToLabel) {
            ForEach(RecipeTab.allCases, id: \.self) { tab in
                Button {
                    withAnimation(.easeInOut(duration: 0.2)) { selectedTab = tab }
                } label: {
                    Text(tab.label)
                        .foregroundStyle(selectedTab == tab ? Sourdough.Colors.ink : Sourdough.Colors.mutedInk)
                        .sourdoughTextStyle(.caption)
                        .frame(maxWidth: .infinity)
                        .frame(height: 36)
                        .background(selectedTab == tab ? Sourdough.Colors.card : Color.clear)
                        .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.tile, style: .continuous))
                        .shadow(color: selectedTab == tab ? Sourdough.Ramp.linen900.opacity(0.08) : .clear, radius: 4, y: 2)
                }
                .buttonStyle(.plain)
            }
        }
        .padding(3)
        .background(Sourdough.Colors.sunken)
        .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.card, style: .continuous))
        .padding(.horizontal, Sourdough.Spacing.screenMargin)
        .padding(.vertical, Sourdough.Spacing.rowInternals)
    }

    // MARK: - Ingredients Section

    private var ingredientsSection: some View {
        let matches = pantryMatchedIngredients
        return VStack(alignment: .leading, spacing: 0) {
            HStack(alignment: .center) {
                VStack(alignment: .leading, spacing: 3) {
                    Text("Ingredients")
                        .foregroundStyle(Sourdough.Colors.ink)
                        .sourdoughTextStyle(.title2)
                    let matchCount = matches.count
                    let total = recipe.ingredientsUsed.count + recipe.missingIngredients.count
                    if matchCount > 0 {
                        Label {
                            Text("You have \(matchCount) of \(total)")
                                .foregroundStyle(Sourdough.Ramp.sage600)
                                .sourdoughTextStyle(.caption)
                        } icon: {
                            Ph.check.regular
                                .frame(width: 12, height: 12)
                        }
                        .foregroundStyle(Sourdough.Ramp.sage600)
                    }
                }
                Spacer()
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)

            Divider()

            ForEach(Array(recipe.ingredientsUsed.enumerated()), id: \.element.id) { index, ingredient in
                ingredientRow(ingredient, match: matches[ingredient.id])
                if index < recipe.ingredientsUsed.count - 1 {
                    Divider()
                        .padding(.leading, Sourdough.Spacing.screenMargin + 44)
                }
            }

            if !recipe.missingIngredients.isEmpty {
                Divider()
                HStack {
                    Label {
                        Text("You'll Need")
                            .foregroundStyle(Sourdough.Colors.mutedInk)
                            .sourdoughTextStyle(.caption)
                    } icon: {
                        Ph.shoppingCart.regular
                            .frame(width: 13, height: 13)
                    }
                        .foregroundStyle(Sourdough.Colors.mutedInk)
                    Spacer()
                    Text("\(recipe.missingIngredients.count) items")
                        .foregroundStyle(Sourdough.Colors.faintInk)
                        .sourdoughTextStyle(.caption)
                }
                .padding(.horizontal, Sourdough.Spacing.screenMargin)
                .padding(.vertical, Sourdough.Spacing.rowInternals)
                Divider()

                ForEach(Array(recipe.missingIngredients.enumerated()), id: \.element.id) { index, ingredient in
                    ingredientRow(ingredient, match: matches[ingredient.id])
                    if index < recipe.missingIngredients.count - 1 {
                        Divider()
                            .padding(.leading, Sourdough.Spacing.screenMargin + 44)
                    }
                }
            }
        }
        .padding(.bottom, Sourdough.Spacing.insideChip)
    }

    // MARK: - Substitutions Section

    private var substitutionsSection: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                Text("Substitutions")
                    .foregroundStyle(Sourdough.Colors.ink)
                    .sourdoughTextStyle(.title2)
                Spacer()
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)

            Divider()

            ForEach(Array(recipe.substitutions.enumerated()), id: \.offset) { index, sub in
                substitutionRow(sub)
                if index < recipe.substitutions.count - 1 {
                    Divider()
                        .padding(.leading, Sourdough.Spacing.screenMargin)
                }
            }
        }
        .padding(.bottom, Sourdough.Spacing.insideChip)
    }

    private func substitutionRow(_ sub: RecipeSubstitution) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: Sourdough.Spacing.insideChip) {
                Text(sub.ingredient)
                    .foregroundStyle(Sourdough.Colors.ink)
                    .sourdoughTextStyle(.rowTitle)
                Ph.arrowRight.regular
                    .frame(width: 11, height: 11)
                    .foregroundStyle(Sourdough.Colors.faintInk)
                Text(sub.substitute)
                    .foregroundStyle(Sourdough.Ramp.sage600)
                    .sourdoughTextStyle(.rowTitle)
            }
            if !sub.note.isEmpty {
                Text(sub.note)
                    .foregroundStyle(Sourdough.Colors.mutedInk)
                    .sourdoughTextStyle(.caption)
            }
        }
        .padding(.horizontal, Sourdough.Spacing.screenMargin)
        .padding(.vertical, Sourdough.Spacing.rowInternals)
    }

    private func ingredientRow(_ ingredient: RecipeIngredient, match: MatchedIngredient?) -> some View {
        let isInPantry = match != nil
        let isChecked = checkedIngredients.contains(ingredient.id)

        return Button {
            guard isCooking else { return }
            withAnimation(.easeInOut(duration: 0.15)) {
                if isChecked { checkedIngredients.remove(ingredient.id) }
                else { checkedIngredients.insert(ingredient.id) }
            }
        } label: {
            HStack(spacing: Sourdough.Spacing.rowInternals) {
                ZStack {
                    if isCooking {
                        Circle()
                            .fill(isChecked ? Sourdough.Ramp.sage500 : Color.clear)
                        Circle()
                            .strokeBorder(isChecked ? Sourdough.Ramp.sage500 : Sourdough.Colors.interactiveBorder, lineWidth: 2)
                        if isChecked {
                            Ph.check.bold
                                .frame(width: 11, height: 11)
                                .foregroundStyle(Sourdough.Colors.onAction)
                        }
                    } else if isInPantry {
                        Circle()
                            .fill(dotColor(for: match?.isSufficient))
                        Ph.check.bold
                            .frame(width: 10, height: 10)
                            .foregroundStyle(Sourdough.Colors.onAction)
                    } else {
                        Circle()
                            .strokeBorder(
                                Sourdough.Colors.interactiveBorder,
                                style: StrokeStyle(lineWidth: 1.5, dash: [4, 2])
                            )
                        Ph.plus.bold
                            .frame(width: 9, height: 9)
                            .foregroundStyle(Sourdough.Colors.faintInk)
                    }
                }
                .frame(width: 28, height: 28)

                Text(ingredient.name.capitalized)
                    .foregroundStyle(isCooking && isChecked ? Sourdough.Colors.faintInk : Sourdough.Colors.ink)
                    .sourdoughTextStyle(.rowTitle)
                    .strikethrough(isCooking && isChecked, color: Sourdough.Colors.faintInk)

                Spacer()

                let trimmedQty = ingredient.quantity.trimmingCharacters(in: .whitespaces)
                if !trimmedQty.isEmpty {
                    Text(trimmedQty)
                        .foregroundStyle(Sourdough.Colors.mutedInk)
                        .sourdoughTextStyle(.numeric)
                        .padding(.horizontal, 10)
                        .padding(.vertical, 4)
                        .background(Sourdough.Colors.sunken)
                        .clipShape(Capsule())
                }
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }

    // MARK: - Steps Section

    private var stepsSection: some View {
        VStack(alignment: .leading, spacing: 0) {
            Divider()
            HStack {
                Text("Instructions")
                    .foregroundStyle(Sourdough.Colors.ink)
                    .sourdoughTextStyle(.title2)
                Spacer()
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)
            Divider()
            VStack(alignment: .leading, spacing: Sourdough.Spacing.screenMargin) {
                ForEach(Array(recipe.steps.enumerated()), id: \.offset) { index, step in
                    HStack(alignment: .top, spacing: Sourdough.Spacing.rowInternals) {
                        Text("\(index + 1)")
                            .foregroundStyle(Sourdough.Colors.onAction)
                            .sourdoughTextStyle(.numeric)
                            .frame(width: 26, height: 26)
                            .background(Sourdough.Ramp.sage500)
                            .clipShape(Circle())
                        Text(step)
                            .foregroundStyle(Sourdough.Colors.ink)
                            .sourdoughTextStyle(.body)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)
        }
    }

    // MARK: - Sources Section

    private var sourcesSection: some View {
        VStack(alignment: .leading, spacing: 0) {
            Divider()
            HStack {
                Text("Sources")
                    .foregroundStyle(Sourdough.Colors.ink)
                    .sourdoughTextStyle(.title2)
                Spacer()
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)
            Divider()
            VStack(alignment: .leading, spacing: Sourdough.Spacing.rowInternals) {
                ForEach(recipe.sources) { source in
                    Link(destination: source.url) {
                        HStack(spacing: Sourdough.Spacing.insideChip) {
                            Ph.arrowSquareOut.regular
                                .frame(width: 14, height: 14)
                                .foregroundStyle(Sourdough.Colors.actionInk)
                            Text(source.title)
                                .foregroundStyle(Sourdough.Colors.actionInk)
                                .sourdoughTextStyle(.body)
                                .lineLimit(1)
                        }
                    }
                }
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.vertical, Sourdough.Spacing.rowInternals)
        }
    }

    // MARK: - Cooking Button (Sticky)

    private var cookingButton: some View {
        HStack(spacing: Sourdough.Spacing.insideChip) {
            Ph.forkKnife.regular
                .frame(width: 16, height: 16)
            Text(isCooking ? "Mark as cooked" : "Start cooking")
                .foregroundStyle(Sourdough.Colors.onAction)
                .sourdoughTextStyle(.rowTitle)
        }
        .foregroundStyle(Sourdough.Colors.onAction)
        .frame(maxWidth: .infinity)
        .frame(height: 56)
        .background(Sourdough.Colors.action)
        .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.pill, style: .continuous))
        .padding(.horizontal, Sourdough.Spacing.screenMargin)
        .padding(.top, Sourdough.Spacing.rowInternals)
        .padding(.bottom, Sourdough.Spacing.aboveSectionHead)
        .background(Sourdough.Colors.canvas.opacity(0.95))
        .onTapGesture {
            if !isCooking {
                withAnimation(.easeInOut(duration: 0.2)) { isCooking = true }
            } else {
                markAsCooked()
                dismiss()
            }
        }
    }

    // MARK: - Pantry Match

    private struct MatchedIngredient: Identifiable {
        var id: UUID { recipeIngredient.id }
        let recipeIngredient: RecipeIngredient
        let pantryIngredient: Ingredient
        let isSufficient: Bool?
    }

    /// Keyed by recipe-ingredient id so `ingredientRow` can look up a match in O(1) instead of
    /// re-scanning the whole pantry-match list once per row.
    private var pantryMatchedIngredients: [UUID: MatchedIngredient] {
        Dictionary(uniqueKeysWithValues: recipe.ingredientsUsed.compactMap { recipeIngredient -> (UUID, MatchedIngredient)? in
            guard let pantry = PantryMatcher.find(for: recipeIngredient.name, in: pantryStore.ingredients) else { return nil }
            let match = MatchedIngredient(
                recipeIngredient: recipeIngredient,
                pantryIngredient: pantry,
                isSufficient: QuantityConverter.isSufficient(
                    have: pantry.totalAmount,
                    need: recipeIngredient.quantity
                )
            )
            return (recipeIngredient.id, match)
        })
    }

    private func dotColor(for sufficient: Bool?) -> Color {
        sufficient == false ? Sourdough.Ramp.honey500 : Sourdough.Ramp.sage500
    }

    private func markAsCooked() {
        for match in pantryMatchedIngredients.values {
            let pantry = match.pantryIngredient
            guard let parsedPantry = QuantityConverter.parse(pantry.totalAmount ?? ""),
                  let parsedNeed = QuantityConverter.parse(match.recipeIngredient.quantity),
                  parsedPantry.unit.category == parsedNeed.unit.category else {
                continue
            }

            let remaining = parsedPantry.toBase() - parsedNeed.toBase()
            if remaining <= 0 {
                pantryStore.useIngredient(id: pantry.id, newAmount: nil)
            } else {
                let newValue = parsedPantry.unit.fromBase(remaining)
                let newAmountStr = "\(QuantityConverter.formatQuantity(newValue)) \(parsedPantry.unit.label)"
                pantryStore.useIngredient(id: pantry.id, newAmount: newAmountStr)
            }
        }
    }

    // MARK: - PDF

    @MainActor
    private func generatePDF() -> URL? {
        let printView = RecipePrintView(recipe: recipe)
            .environment(\.colorScheme, .light)

        let renderer = ImageRenderer(content: printView)
        renderer.proposedSize = .init(width: 612, height: nil)

        let url = FileManager.default.temporaryDirectory.appendingPathComponent("\(recipe.title).pdf")

        renderer.render { size, renderInContext in
            var box = CGRect(origin: .zero, size: size)
            guard let context = CGContext(url as CFURL, mediaBox: &box, nil) else { return }
            context.beginPDFPage(nil)
            renderInContext(context)
            context.endPDFPage()
            context.closePDF()
        }

        return FileManager.default.fileExists(atPath: url.path) ? url : nil
    }
}

// MARK: - Rate Recipe Sheet

private struct RateRecipeSheet: View {
    @Environment(\.dismiss) private var dismiss
    let recipe: Recipe
    @State private var selectedRating: Int
    @State private var reviewText: String
    @State private var moderationError: String?
    let onSubmit: (Int, String?) -> Void

    init(recipe: Recipe, currentRating: Int, currentReview: String, onSubmit: @escaping (Int, String?) -> Void) {
        self.recipe = recipe
        self._selectedRating = State(initialValue: currentRating)
        self._reviewText = State(initialValue: currentReview)
        self.onSubmit = onSubmit
    }

    var body: some View {
        VStack(spacing: 0) {
            Capsule()
                .fill(Sourdough.Colors.hairline)
                .frame(width: 36, height: 5)
                .padding(.top, Sourdough.Spacing.rowInternals)
                .padding(.bottom, Sourdough.Spacing.betweenBlocks)

            VStack(spacing: Sourdough.Spacing.screenMargin) {
                HStack {
                    Text("Rate This Recipe")
                        .foregroundStyle(Sourdough.Colors.ink)
                        .sourdoughTextStyle(.title1)
                    Spacer()
                    Button("Cancel") { dismiss() }
                        .foregroundStyle(Sourdough.Colors.mutedInk)
                        .sourdoughTextStyle(.caption)
                        .buttonStyle(.plain)
                }

                VStack(spacing: Sourdough.Spacing.insideChip) {
                    Text("Tap a star to rate")
                        .foregroundStyle(Sourdough.Colors.faintInk)
                        .sourdoughTextStyle(.caption)

                    StarRatingView(rating: Double(selectedRating), size: 40, interactive: true) { newRating in
                        selectedRating = newRating
                    }
                }

                VStack(alignment: .leading, spacing: Sourdough.Spacing.insideChip) {
                    Text("Leave a comment (optional)")
                        .foregroundStyle(Sourdough.Colors.mutedInk)
                        .sourdoughTextStyle(.caption)

                    TextField("What did you think?", text: $reviewText, axis: .vertical)
                        .lineLimit(3...6)
                        .foregroundStyle(Sourdough.Colors.ink)
                        .sourdoughTextStyle(.body)
                        .padding(Sourdough.Spacing.rowInternals)
                        .background(Sourdough.Colors.sunken)
                        .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.card, style: .continuous))

                    if let moderationError {
                        Text(moderationError)
                            .foregroundStyle(Sourdough.Colors.destructive)
                            .sourdoughTextStyle(.caption)
                    }
                }
            }
            .padding(.horizontal, Sourdough.Spacing.screenMargin)

            Spacer()

            Button {
                guard !ContentModerationFilter.containsObjectionableContent(reviewText) else {
                    moderationError = "Your comment contains language that isn't allowed. Please revise it and try again."
                    return
                }
                onSubmit(selectedRating, reviewText.isEmpty ? nil : reviewText)
                dismiss()
            } label: {
                Text("Submit")
                    .foregroundStyle(Sourdough.Colors.onAction)
                    .sourdoughTextStyle(.rowTitle)
                    .frame(maxWidth: .infinity)
                    .frame(height: 52)
                    .background(selectedRating > 0 ? Sourdough.Colors.action : Sourdough.Colors.action.opacity(0.4))
                    .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.pill, style: .continuous))
            }
            .buttonStyle(.plain)
            .disabled(selectedRating == 0)
            .padding(.horizontal, Sourdough.Spacing.screenMargin)
            .padding(.top, Sourdough.Spacing.rowInternals)
            .padding(.bottom, Sourdough.Spacing.rowInternals)
        }
        .background(Sourdough.Colors.canvas)
    }
}

// MARK: - Recipe Print View

private struct RecipePrintView: View {
    let recipe: Recipe

    var body: some View {
        VStack(alignment: .leading, spacing: Sourdough.Spacing.screenMargin) {
            Text(recipe.title)
                .foregroundStyle(Sourdough.Ramp.linen900)
                .sourdoughTextStyle(.title1)

            Text(recipe.summary)
                .foregroundStyle(Sourdough.Ramp.linen500)
                .sourdoughTextStyle(.subhead)

            HStack(spacing: Sourdough.Spacing.screenMargin) {
                Label {
                    Text("\(recipe.timeMinutes) min")
                } icon: {
                    Ph.clock.regular
                        .frame(width: 12, height: 12)
                }
                Label {
                    Text("\(recipe.servings) servings")
                } icon: {
                    Ph.users.regular
                        .frame(width: 12, height: 12)
                }
                Label {
                    Text(recipe.cuisine.rawValue)
                } icon: {
                    Ph.forkKnife.regular
                        .frame(width: 12, height: 12)
                }
            }
            .foregroundStyle(Sourdough.Ramp.linen400)
            .sourdoughTextStyle(.caption)

            if recipe.dietType != "any" || !recipe.dietaryRestrictions.isEmpty {
                let chips = (recipe.dietType != "any" ? [recipe.dietType.capitalized] : []) + recipe.dietaryRestrictions
                HStack(spacing: Sourdough.Spacing.insideChip) {
                    ForEach(chips, id: \.self) { chip in
                        Text(chip)
                            .foregroundStyle(Sourdough.Ramp.sage600)
                            .sourdoughTextStyle(.caption)
                            .padding(.horizontal, Sourdough.Spacing.rowInternals)
                            .padding(.vertical, 4)
                            .background(Sourdough.Ramp.sage100)
                            .clipShape(Capsule())
                    }
                }
            }

            VStack(alignment: .leading, spacing: Sourdough.Spacing.rowInternals) {
                HStack(spacing: Sourdough.Spacing.insideChip) {
                    Ph.basket.fill
                        .frame(width: 14, height: 14)
                        .foregroundStyle(Sourdough.Ramp.terracotta500)
                    Text("Ingredients")
                        .foregroundStyle(Sourdough.Ramp.linen500)
                        .sourdoughTextStyle(.sectionHead)
                }
                ForEach(recipe.ingredientsUsed) { ingredient in
                    HStack(spacing: Sourdough.Spacing.insideChip) {
                        Circle()
                            .fill(Sourdough.Ramp.terracotta500)
                            .frame(width: 6, height: 6)
                        Text(ingredient.displayText)
                            .foregroundStyle(Sourdough.Ramp.linen900)
                            .sourdoughTextStyle(.subhead)
                    }
                }
            }
            .padding(Sourdough.Spacing.screenMargin)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Sourdough.Ramp.linen100)
            .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.hero, style: .continuous))

            if !recipe.missingIngredients.isEmpty {
                VStack(alignment: .leading, spacing: Sourdough.Spacing.rowInternals) {
                    HStack(spacing: Sourdough.Spacing.insideChip) {
                        Ph.shoppingCart.fill
                            .frame(width: 14, height: 14)
                            .foregroundStyle(Sourdough.Ramp.honey600)
                        Text("Missing Ingredients")
                            .foregroundStyle(Sourdough.Ramp.linen500)
                            .sourdoughTextStyle(.sectionHead)
                    }
                    ForEach(recipe.missingIngredients) { ingredient in
                        HStack(spacing: Sourdough.Spacing.insideChip) {
                            Circle()
                                .fill(Sourdough.Ramp.honey600)
                                .frame(width: 6, height: 6)
                            Text(ingredient.displayText)
                                .foregroundStyle(Sourdough.Ramp.linen500)
                                .sourdoughTextStyle(.subhead)
                        }
                    }
                }
                .padding(Sourdough.Spacing.screenMargin)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Sourdough.Ramp.linen100)
                .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.hero, style: .continuous))
            }

            VStack(alignment: .leading, spacing: Sourdough.Spacing.rowInternals) {
                HStack(spacing: Sourdough.Spacing.insideChip) {
                    Ph.listNumbers.regular
                        .frame(width: 14, height: 14)
                        .foregroundStyle(Sourdough.Ramp.terracotta500)
                    Text("Steps")
                        .foregroundStyle(Sourdough.Ramp.linen500)
                        .sourdoughTextStyle(.sectionHead)
                }
                VStack(alignment: .leading, spacing: Sourdough.Spacing.screenMargin) {
                    ForEach(Array(recipe.steps.enumerated()), id: \.offset) { index, step in
                        HStack(alignment: .top, spacing: Sourdough.Spacing.rowInternals) {
                            Text("\(index + 1)")
                                .foregroundStyle(Sourdough.Ramp.onFilled)
                                .sourdoughTextStyle(.subhead)
                                .frame(width: 24, height: 24)
                                .background(Sourdough.Ramp.terracotta500)
                                .clipShape(Circle())
                            Text(step)
                                .foregroundStyle(Sourdough.Ramp.linen900)
                                .sourdoughTextStyle(.subhead)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                }
            }
            .padding(Sourdough.Spacing.screenMargin)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(Sourdough.Ramp.linen100)
            .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.hero, style: .continuous))

            if !recipe.sources.isEmpty {
                VStack(alignment: .leading, spacing: Sourdough.Spacing.rowInternals) {
                    HStack(spacing: Sourdough.Spacing.insideChip) {
                        Ph.arrowSquareOut.regular
                            .frame(width: 14, height: 14)
                            .foregroundStyle(Sourdough.Ramp.terracotta500)
                        Text("Sources")
                            .foregroundStyle(Sourdough.Ramp.linen500)
                            .sourdoughTextStyle(.sectionHead)
                    }
                    ForEach(recipe.sources) { source in
                        HStack(spacing: Sourdough.Spacing.insideChip) {
                            Ph.arrowSquareOut.regular
                                .frame(width: 12, height: 12)
                                .foregroundStyle(Sourdough.Ramp.linen400)
                            Text(source.title)
                                .foregroundStyle(Sourdough.Ramp.linen900)
                                .sourdoughTextStyle(.subhead)
                                .lineLimit(1)
                        }
                    }
                }
                .padding(Sourdough.Spacing.screenMargin)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Sourdough.Ramp.linen100)
                .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.hero, style: .continuous))
            }

            HStack(spacing: Sourdough.Spacing.screenMargin) {
                macroItem(label: "Calories", value: "\(recipe.macros.calories)", color: Sourdough.Ramp.terracotta500)
                macroItem(label: "Protein", value: "\(recipe.macros.proteinG)g", color: Sourdough.Ramp.sage600)
                macroItem(label: "Carbs", value: "\(recipe.macros.carbsG)g", color: Sourdough.Ramp.honey600)
                macroItem(label: "Fat", value: "\(recipe.macros.fatG)g", color: Sourdough.Ramp.destructive)
            }

            Text("Shared from Use Up")
                .foregroundStyle(Sourdough.Ramp.linen400)
                .sourdoughTextStyle(.caption)
                .frame(maxWidth: .infinity, alignment: .center)
        }
        .padding(Sourdough.Spacing.screenMargin)
        .background(Sourdough.Ramp.linen50)
    }

    private func macroItem(label: String, value: String, color: Color) -> some View {
        VStack(spacing: 4) {
            Text(value)
                .foregroundStyle(color)
                .sourdoughTextStyle(.subhead)
            Text(label)
                .foregroundStyle(Sourdough.Ramp.linen400)
                .sourdoughTextStyle(.caption)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, Sourdough.Spacing.insideChip)
        .background(color.opacity(0.08))
        .clipShape(RoundedRectangle(cornerRadius: Sourdough.Radius.tile, style: .continuous))
    }
}

// MARK: - Share Sheet

struct ShareSheet: UIViewControllerRepresentable {
    let items: [Any]

    func makeUIViewController(context: Context) -> UIActivityViewController {
        UIActivityViewController(activityItems: items, applicationActivities: nil)
    }

    func updateUIViewController(_ uiViewController: UIActivityViewController, context: Context) {}
}
